# Site Info
title: 콩로그.net
tagline: '개발을 잘하고 싶은 저장소'
description: '프론트엔드기술 HTML5, CSS, Javascript, 프로그래밍 언어 그리고 IT 기술을 연구하는 블로그입니다.'
baseurl: ""
url: http://my2kong.net
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 콩이아빠
  description: 생계형 프론트엔드 개발자.
  gravatar: 971e5f01f7cfad2974a6d361803d0778 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/my2kong/
    facebook:
    twitter:   https://twitter.com/my2kong
    # weibo:     http://weibo.com/41173780
    email:     mailto:my2kong@naver.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    # - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
#  Github Project:
#    - 'http://my2kong.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-79918749-1' # leave blank if you don't want google analytics
disqus_short_name: 'my2kong' # leave blank if you don't want disqus

